### ISSUE TITLE
BUG: Floating point doctest fails when it shouldn't

### ISSUE THREAD

**Issue by mcara** [astropy/pytest-doctestplus#135] opened 2020-11-18 19:22 UTC
I have a PR whose docstring test fails for apparently no reason. https://travis-ci.com/github/spacetelescope/gwcs/jobs/442526367#L333-L350:

```
-[[1.00000039e+00 1.99999827e+00]
+[[1.00000040e+00 1.99999841e+00]
```
and
```
-[[2.75846364e-05 1.15157818e-05]
+[[2.75925982e-05 1.18471543e-05]
```
The tests were passing locally on Mac OSX but failing on Linux. That was until I discovered that Tavis is using `pytest-doctestplus` version `0.8.0` while I had `0.3.0`. Local tests pass up to `0.4.0` and start failing after `>=0.5.0`. What has changed from `0.4.0` to `0.5.0` that would make these comparisons fail.

At the same time:
```python
In [1]: from pytest_doctestplus.output_checker import OutputChecker, FLOAT_CMP

In [2]: OutputChecker().normalize_floats('1.99999827e+00', '1.99999841e+00', FLOAT_CMP)
Out[2]: True

In [3]: OutputChecker().normalize_floats('2.75846364e-05', '2.75925982e-05', FLOAT_CMP)
Out[3]: True
```

**Comment by pllim** [comment] 2020-11-18 19:26
Instead of `FLOAT_CMP`, you can use https://docs.python.org/3.8/library/doctest.html#doctest.ELLIPSIS instead .

**Comment by astrofrog** [comment] 2020-11-19 12:13
I think there is a real bug worth fixing here though

**Comment by mcara** [comment] 2020-11-19 13:09
I do not know what is the bug. I looked at the code and it looks to me that the behavior has changed after #79: line https://github.com/astropy/pytest-doctestplus/pull/79/files#diff-d90c0c447b2717b3b0a9e5c28a5d94b56400aada74599978ca9f213949ca7326R99 was moved after the `if` statement.

The code itself is very confusing to read: it defines two variables that based on their names should be related as `a = not b` but they are not: `run_regular_doctest` and `use_doctest_plus`.

In the end, after reading `readme.rst`:
> Using `pytest`'s built-in `--doctest-modules` option will override the behavior of this plugin, even if `doctest_plus = enabled` in `setup.cfg`, and will cause the default `doctest` plugin to be used. However, if for some reason both `--doctest-modules` and `--doctest-plus` are given, the `pytest-doctestplus` plugin will be used, regardless of the contents of `setup.cfg`

I thought that moving `doctest.OutputChecker = OutputChecker` after `if` was consistent with the above comment.

**Comment by saimn** [comment] 2020-11-19 13:20
Not sure to understand everything above about the different versions, but with the data you give it's expected that the comparison fail, with the tolerance that are used by the plugin:
```
In [13]: np.isclose([2.75846364e-05, 1.15157818e-05], [2.75925982e-05, 1.18471543e-05], rtol=1e-5, atol=1e-8)
Out[13]: array([ True, False])
```

**Comment by mcara** [comment] 2020-11-19 13:24
I do not think these are the data, @saimn 

```python
In [2]: np.isclose([1.99999827, 2.75846364e-05], [1.99999841, 2.75925982e-05], rtol=1e-5, atol=1e-8)
Out[2]: array([ True,  True])
```

**Comment by mcara** [comment] 2020-11-19 13:28
I see, it fails for the pair `1.15157818e-05, 1.18471543e-05` but it should be fine for the first line:
```
-[[1.00000039e+00 1.99999827e+00]
+[[1.00000040e+00 1.99999841e+00]
```
but it fails there too.

**Comment by saimn** [comment] 2020-11-19 14:12
Yes, the first example should be ok, but maybe that's just an issue with the report of differences. The second example (_Achieved accuracy_) should fail.

**Comment by bsipocz** [comment] 2022-10-02 05:25
Hmm, I'm sorry for the noise with the title. I've thought I could reproduce the failure, but apparently I was instead missing an import in failing my example.

Anyway, if I go to the gwcs docs atm, and remove the SKIP, indeed the line still fails, but I firmly believe the issue is with the fact that `FLOAT_CMP` was put on the wrong line, it's on `try:` rather than the line that actually produces the output, therefore it has no effect. I open a PR for this change, feel free to close it if you rather keep the skip.

(FLOAT_CMP could of course be set globally, in fact, I think that's a much nicer way to do it than on the per line level, but I didn't go that far to change the default)

**Closed by bsipocz** 2022-10-02 05:25 UTC
Labels: bug
