### ISSUE TITLE
`TypeError` on collection with pytest 7.0

### ISSUE THREAD

**Issue by astrojuanlu** [astropy/pytest-doctestplus#170] opened 2021-12-07 11:53 UTC
Just tried running poliastro test suite with pytest 7.0.0rc1 and found this error:

```
py38-fast run-test: commands[1] | pytest -m 'not slow and not mpl_image_compare' --mypy -vv
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.8.10, pytest-7.0.0rc1, pluggy-1.0.0 -- /home/juanlu/Projects/LSF/poliastro/library/.tox/py38-fast/bin/python
cachedir: .tox/py38-fast/.pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/juanlu/Projects/LSF/poliastro/library/.hypothesis/examples')
Matplotlib: 3.5.0
Freetype: 2.6.1
rootdir: /home/juanlu/Projects/LSF/poliastro/library, configfile: setup.cfg, testpaths: src, tests
plugins: hypothesis-6.30.1, remotedata-0.3.2, mypy-0.8.1, doctestplus-0.11.1, mpl-0.13, cov-2.5.1
collected 1172 items / 1 error / 33 deselected / 1138 selected                                                                                                                                                                               

=================================================================================================================== ERRORS ===================================================================================================================
_____________________________________________________________________________________________________ ERROR collecting tests/conftest.py _____________________________________________________________________________________________________
.tox/py38-fast/lib/python3.8/site-packages/pytest_doctestplus/plugin.py:210: in collect
    module = self.config.pluginmanager._importconftest(
E   TypeError: _importconftest() missing 1 required positional argument: 'rootpath'

```

It doesn't happen with pytest 6.2.5.

**Comment by Cadair** [comment] 2021-12-07 14:56
Can reproduce on the sunpy suite as well.

**Comment by saimn** [comment] 2021-12-07 15:11
It should be fixed on main. So now that there is a new release coming we should check that our tests pass with it and make a new release.

**Comment by saimn** [comment] 2021-12-07 16:11
I forgot there was already a release recently (0.11.1), so probably some more breaking changes were merged on pytest since that.

**Closed** 2021-12-07 19:25 UTC

**Comment by pllim** [comment] 2021-12-07 19:30
Whoever doing the next release, the workflow didn't kick off when I pushed a new tag the last time. If it happens again, the workflow needs to be fixed.

**Comment by saimn** [comment] 2021-12-09 18:12
0.11.2 is on PyPI :tada: (and no issues with the release workflow!)

**Comment by pllim** [comment] 2021-12-09 18:26
Phew. Thanks!
