### ISSUE TITLE
Why is there testsetup but no testcleanup?

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-doctestplus#164] opened 2021-09-15 13:11 UTC
https://github.com/astropy/pytest-doctestplus/blob/16d6d4527439516d5a370b34941e4f1f549268f5/pytest_doctestplus/sphinx/doctestplus.py#L54

There appears to be no support for `testcleanup` directive even though this package is supposed to expand on the existing `doctest` module from upstream. As a result: https://github.com/astropy/astropy/pull/12150#issuecomment-918575446

**Comment by saimn** [comment] 2021-09-15 14:37
`testsetup` comes from https://github.com/astropy/sphinx-astropy/commit/4259159891d820e1bdc6ab884356e05332976c17 but there is no real explanation about why it was added. But this directive is doing nothing I guess, just avoiding the sphinx build to test if the sphinx extension is not present.

`testcode`/`testsetup` etc. come from the sphinx doctest extension (https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html) so those doctest can be only be run with sphinx. And pytest-doctestplus is using another format to have doctest run with pytest, so 2 different things.

Pytest itself doesn't support sphinx's doctest (https://github.com/pytest-dev/pytest/issues/2514) but from this ticket I see there is a pytest-sphinx plugin (https://github.com/thisch/pytest-sphinx).

Maybe we should point to that alternative in the README for people willing to use `testcode` ? Also this issue is kind of a duplicate of https://github.com/astropy/pytest-doctestplus/issues/106

**Comment by pllim** [comment] 2021-09-15 15:08
So, can I use `pytest-doctestplus` and `sphinx.ext.doctest` together? All I want is to be able to run some clean-up code at the end of the RST page, while still utilizing features from this plugin. Currently, I see that `sphinx-astropy` does not automatically add `sphinx.ext.doctest` to its `conf.py` and I don't know if there was a specific reason for not having it there.

**Comment by pllim** [comment] 2021-09-15 15:08
I am not sure if this is duplicate of #106. I have no desire to use `testcode`.

**Comment by saimn** [comment] 2021-09-15 15:30
pytest-doctestplus does not know about sphinx's directives, so `testclean` etc. can only be used with `testcode` and the sphinx extension.

**Comment by pllim** [comment] 2021-09-15 15:36
Now I am confused... `testsetup` seems to work for me at https://raw.githubusercontent.com/spacetelescope/stsynphot_refactor/master/docs/stsynphot/tutorials.rst . I didn't have to explicitly use `sphinx.ext.doctest`, though I also did not try to use `testcleanup`. I also did not use `testcode`.

**Comment by saimn** [comment] 2021-09-15 16:06
Oh OK, I think this is because you are using the `>>>`. Since we use Python's doctest parser it will look for all the code block starting with `>>>` and we execute it. And then 
```
app.add_directive('testsetup', DoctestOmitDirective, override=True)
```
just tells Sphinx to not render those lines. So we could do the same with `testclean`. But this is quite confusing because those directive are initially defined in the Sphinx extension where there are not supposed to be used with `>>>` ...

**Comment by pllim** [comment] 2021-09-15 16:09
> this is quite confusing

Confusing but works is better than nothing, right? 😅 

We can try to explain in the README here... 🤷

**Closed** 2021-09-17 20:41 UTC
